version: "3.2"

services:
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: opds
      MYSQL_USER: darvik
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
